-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."OU_roles"
(
    "PK_role_id" bigserial,
    role_name character varying(50) NOT NULL,
    PRIMARY KEY ("PK_role_id"),
    CONSTRAINT role_name UNIQUE (role_name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_functions"
(
    "PK_function_id" bigserial,
    function_name character varying(50) NOT NULL,
    PRIMARY KEY ("PK_function_id"),
    CONSTRAINT function_name UNIQUE (function_name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_roles_with_functions"
(
    "PK_FK_role_id" bigint,
    "PK_FK_function_id" bigint,
    PRIMARY KEY ("PK_FK_role_id", "PK_FK_function_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_users"
(
    "PK_user_id" bigserial,
    user_email character varying(320) NOT NULL,
    encrypted_password character varying(100) NOT NULL,
    "FK_role_id" bigint NOT NULL,
    PRIMARY KEY ("PK_user_id"),
    CONSTRAINT user_email UNIQUE (user_email)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_orders"
(
    "PK_order_id" bigserial,
    payment_method character(4) NOT NULL,
    time_stamp timestamp without time zone NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    "FK_user_id" bigint NOT NULL,
    PRIMARY KEY ("PK_order_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_seats"
(
    "PK_seat_id" bigserial,
    seat_number smallint NOT NULL,
    seat_type character(5) NOT NULL,
    PRIMARY KEY ("PK_seat_id"),
    CONSTRAINT number_type UNIQUE (seat_number, seat_type)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_coach_types"
(
    "PK_coach_type_id" bigserial,
    coach_type_name character varying(50) NOT NULL,
    PRIMARY KEY ("PK_coach_type_id"),
    CONSTRAINT coach_type_name UNIQUE (coach_type_name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_coach_types_with_seats"
(
    "PK_FK_seat_id" bigint,
    "PK_FK_coach_type_id" bigint,
    PRIMARY KEY ("PK_FK_seat_id", "PK_FK_coach_type_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_trains"
(
    "PK_train_id" bigserial,
    train_code character varying(50) NOT NULL,
    train_name character varying(255) NOT NULL,
    transporter character varying(255) NOT NULL,
    train_rank smallint NOT NULL,
    PRIMARY KEY ("PK_train_id"),
    CONSTRAINT train_code UNIQUE (train_code)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_coaches"
(
    "PK_coach_id" bigserial,
    coach_code character varying(50) NOT NULL,
    coach_number bigint NOT NULL,
    "FK_train_id" bigint NOT NULL,
    "FK_coach_type_id" bigint NOT NULL,
    PRIMARY KEY ("PK_coach_id"),
    CONSTRAINT coach_code UNIQUE (coach_code)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_stations"
(
    "PK_station_id" bigserial,
    station_name character varying(255) NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    PRIMARY KEY ("PK_station_id"),
    CONSTRAINT coord UNIQUE (lat, lon)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_routes_by_stations"
(
    "PK_FK_route_id" bigint NOT NULL,
    "PK_FK_station_id" bigint NOT NULL,
    arrival_time time without time zone NOT NULL,
    departure_time time without time zone NOT NULL,
    station_order_number integer NOT NULL,
    distance_back integer NOT NULL,
    PRIMARY KEY ("PK_FK_route_id", "PK_FK_station_id"),
    CONSTRAINT route_with_station UNIQUE ("PK_FK_route_id", "PK_FK_station_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_trips"
(
    "PK_trip_id" bigserial,
    "FK_route_id" bigint NOT NULL,
    "FK_train_id" bigint NOT NULL,
    PRIMARY KEY ("PK_trip_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_documents"
(
    "PK_document_id" bigserial,
    doc_type smallint NOT NULL,
    doc_code character varying(50) NOT NULL,
    "FK_passenger_id" bigint NOT NULL,
    PRIMARY KEY ("PK_document_id"),
    CONSTRAINT doc_code UNIQUE (doc_code)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_passengers"
(
    "PK_passenger_id" bigserial,
    passenger_name character varying(75) NOT NULL,
    surname character varying(75) NOT NULL,
    patronymic character varying(75),
    sex character(1) NOT NULL,
    birthdate date NOT NULL,
    phone_number character varying(15),
    passenger_email character varying(320) NOT NULL,
    organisation character varying(255),
    PRIMARY KEY ("PK_passenger_id"),
    CONSTRAINT " passenger_email" UNIQUE (passenger_email)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_tickets"
(
    "PK_ticket_id" bigserial,
    departure_time timestamp without time zone NOT NULL,
    arrival_time timestamp without time zone NOT NULL,
    coach_number bigint NOT NULL,
    seat_number smallint NOT NULL,
    from_station character varying(255) NOT NULL,
    to_station character varying(255) NOT NULL,
    price bigint NOT NULL,
    status character varying(50) NOT NULL,
    "FK_order_id" bigint NOT NULL,
    "FK_trip_id" bigint NOT NULL,
    "FK_passenger_id" bigint NOT NULL,
    PRIMARY KEY ("PK_ticket_id"),
    CONSTRAINT departure_time_passenger UNIQUE (departure_time, "FK_passenger_id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_transactions"
(
    "PK_transaction_id" bigserial,
    transaction_code character varying(50) NOT NULL,
    transaction_type character varying(50) NOT NULL,
    sender_account character varying(50) NOT NULL,
    payment_system character varying(50) NOT NULL,
    card_type character varying(50) NOT NULL,
    actual_amount bigint NOT NULL,
    actual_currency character(3) NOT NULL,
    time_stamp timestamp without time zone NOT NULL,
    status character varying(50) NOT NULL,
    "FK_ticket_id" bigint NOT NULL,
    PRIMARY KEY ("PK_transaction_id"),
    CONSTRAINT transaction_code UNIQUE (transaction_code)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public."OU_routes"
(
    "PK_route_id" bigserial,
    route_name character varying(255) NOT NULL,
    PRIMARY KEY ("PK_route_id")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public."OU_roles_with_functions"
    ADD CONSTRAINT role FOREIGN KEY ("PK_FK_role_id")
    REFERENCES public."OU_roles" ("PK_role_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_roles_with_functions"
    ADD CONSTRAINT function FOREIGN KEY ("PK_FK_function_id")
    REFERENCES public."OU_functions" ("PK_function_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_users"
    ADD CONSTRAINT role FOREIGN KEY ("FK_role_id")
    REFERENCES public."OU_roles" ("PK_role_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_orders"
    ADD CONSTRAINT "user" FOREIGN KEY ("FK_user_id")
    REFERENCES public."OU_users" ("PK_user_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_coach_types_with_seats"
    ADD CONSTRAINT seat FOREIGN KEY ("PK_FK_seat_id")
    REFERENCES public."OU_seats" ("PK_seat_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_coach_types_with_seats"
    ADD CONSTRAINT coach_type FOREIGN KEY ("PK_FK_coach_type_id")
    REFERENCES public."OU_coach_types" ("PK_coach_type_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_coaches"
    ADD CONSTRAINT train FOREIGN KEY ("FK_train_id")
    REFERENCES public."OU_trains" ("PK_train_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_coaches"
    ADD CONSTRAINT coach_type FOREIGN KEY ("FK_coach_type_id")
    REFERENCES public."OU_coach_types" ("PK_coach_type_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_routes_by_stations"
    ADD CONSTRAINT station FOREIGN KEY ("PK_FK_station_id")
    REFERENCES public."OU_stations" ("PK_station_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_routes_by_stations"
    ADD CONSTRAINT route FOREIGN KEY ("PK_FK_route_id")
    REFERENCES public."OU_routes" ("PK_route_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_trips"
    ADD CONSTRAINT train FOREIGN KEY ("FK_train_id")
    REFERENCES public."OU_trains" ("PK_train_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_trips"
    ADD CONSTRAINT route FOREIGN KEY ("FK_route_id")
    REFERENCES public."OU_routes" ("PK_route_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_documents"
    ADD CONSTRAINT passenger FOREIGN KEY ("FK_passenger_id")
    REFERENCES public."OU_passengers" ("PK_passenger_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_tickets"
    ADD CONSTRAINT passenger FOREIGN KEY ("FK_passenger_id")
    REFERENCES public."OU_passengers" ("PK_passenger_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_tickets"
    ADD CONSTRAINT trip FOREIGN KEY ("FK_trip_id")
    REFERENCES public."OU_trips" ("PK_trip_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_tickets"
    ADD CONSTRAINT "order" FOREIGN KEY ("FK_order_id")
    REFERENCES public."OU_orders" ("PK_order_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OU_transactions"
    ADD CONSTRAINT ticket FOREIGN KEY ("FK_ticket_id")
    REFERENCES public."OU_tickets" ("PK_ticket_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;